"""Chemical identity handling: InChIKeys and compound names.

This module is deliberately dependency-free. Everything SPECGAP does rests on
InChIKey identity, so the rules here are stated explicitly rather than
inherited from a cheminformatics toolkit's defaults.
"""
from __future__ import annotations

import difflib
import re

# An InChIKey is 27 characters: 14-char skeleton block, 10-char block encoding
# stereochemistry/isotopes/protonation, then 1 char for the protonation and
# InChI version flag. Example: HZGJWEZZXLGUAU-UHFFFAOYSA-N
INCHIKEY_RE = re.compile(r"^[A-Z]{14}-[A-Z]{10}-[A-Z]$")

# Standard InChI (as opposed to non-standard) is flagged by 'S' as the 9th
# character of the second block. GNPS/MoNA contain a small number of
# non-standard keys; they still match structurally but are worth counting.
_STANDARD_FLAG_POS = 8

# Salt, hydrate and counter-ion words that spectral libraries append to
# compound names but structure databases usually do not.
_SALT_WORDS = (
    "hydrate", "dihydrate", "trihydrate", "monohydrate",
    "hydrochloride", "hydrobromide", "hcl", "hbr",
    "sodium", "potassium", "calcium", "magnesium", "ammonium",
    "sulfate", "sulphate", "phosphate", "acetate", "citrate",
    "mesylate", "tosylate", "maleate", "tartrate", "oxalate",
    "salt", "anhydrous",
)
_SALT_RE = re.compile(r"\b(" + "|".join(_SALT_WORDS) + r")\b")

# Adduct notation GNPS appends to NAME, e.g. "Desferrioxamine B M+H",
# "Bortezomib (Velcade) [M+Na]". These are measurement artifacts, not part of
# the compound's identity, and must be stripped before matching names.
_ADDUCT_RE = re.compile(
    r"(\[\s*\d*\s*M[^\]]*\]\s*[+-]?\d*[+-]?)"      # bracketed: [M+H]+, [2M-H]-
    r"|(?:(?<=\s)\d*M\s*[+-]\s*[A-Za-z0-9]+\s*$)",  # bare trailing: M+H, 2M-Na
)


def is_wellformed_inchikey(value: str | None) -> bool:
    """True if `value` has valid InChIKey syntax. Does not verify chemistry."""
    return bool(value) and bool(INCHIKEY_RE.match(value.strip().upper()))


def skeleton(inchikey: str) -> str:
    """First (connectivity) block of an InChIKey.

    Two compounds sharing a skeleton have the same molecular graph but may
    differ in stereochemistry, isotopic labelling or protonation. Spectral
    libraries frequently cannot resolve stereochemistry, so skeleton-level
    matching is the looser, more permissive coverage criterion. See
    docs/LIMITATIONS.md before using it as a headline number.
    """
    return inchikey.strip().upper().split("-")[0]


def is_standard_inchikey(inchikey: str) -> bool:
    """True if the key was generated by standard InChI (flag 'S')."""
    parts = inchikey.strip().upper().split("-")
    return (
        len(parts) == 3
        and len(parts[1]) == 10
        and parts[1][_STANDARD_FLAG_POS] == "S"
    )


def strip_adduct(name: str) -> str:
    """Remove trailing adduct notation from a spectral-library compound name.

    GNPS stores names like 'Desferrioxamine B M+H' or
    'Bortezomib (Velcade) [M+Na]'. The adduct describes the measured ion, not
    the compound, and will never appear in a structure database's name field.
    """
    return _ADDUCT_RE.sub("", name).strip(" -")


def normalize_name(name: str | None) -> str:
    """Casefold, strip adducts and salt words, collapse punctuation.

    Returns '' for empty or placeholder names. GNPS and MoNA both use the
    literal string 'N/A' as a null, which must not be treated as a name (or
    every N/A record would spuriously match every other N/A record).
    """
    if not name:
        return ""
    name = name.strip()
    if name.upper() in {"N/A", "NA", "NONE", "NULL", "UNKNOWN", "-", ""}:
        return ""
    name = strip_adduct(name)
    name = name.lower()
    name = _SALT_RE.sub(" ", name)
    name = re.sub(r"[^a-z0-9]+", " ", name)
    return re.sub(r"\s+", " ", name).strip()


def name_matches(
    declared: str | None,
    candidates: set[str],
    fuzzy_threshold: float = 0.92,
) -> tuple[bool, str]:
    """Can `declared` be reconciled with any known name for this structure?

    `candidates` must already be normalized. Returns (matched, method) where
    method is 'exact', 'fuzzy:<ratio>', or 'none'. An empty declared name or
    empty candidate set is never a match — absence of evidence is not a match.
    """
    norm = normalize_name(declared)
    if not norm or not candidates:
        return False, "none"
    if norm in candidates:
        return True, "exact"
    best_ratio, best = 0.0, None
    for cand in candidates:
        if not cand:
            continue
        ratio = difflib.SequenceMatcher(None, norm, cand).ratio()
        if ratio > best_ratio:
            best_ratio, best = ratio, cand
    if best_ratio >= fuzzy_threshold:
        return True, f"fuzzy:{best_ratio:.3f}"
    return False, "none"
